// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FZNb9tGEP0rxLRHSqQsp1Z5amMUrdG6LuLmVBjFmByJG5O7zOxQjSvwvxe7pGhRpJUUSIIcchHE4ex8",
	"vHnzuDtITVkZTVosJDuwaU4l+r8/MRt+RbYy2pIzVGwqYlHkX5dkLW78C3qHZVUQJKD0FguVBVSiKgLD",
	"QYXW/mM4gxDksXIuVljpDTRNCExva8WUQfJXH+6udzT3bygVaEK4pufLqC3x3yoblhEvVuvF2fJ89uK7",
	"i9XsAu/T2Sqj9Sx2Rmf7Hu/fW9E+8lRFt2qjlX5Fb2uyMi7Ktz8syUX7oXucp6aEENaGSxRIOvdRPSH0",
	"6A1C7a2LsyWEUCr9G+mN5JCs3tfSPlEf91RvXxLizlPptXFJU6MFUznAGR6MIJu5EXzAAchNCBnZlFUl",
	"ymhI4KYi/eMfVxBCoVLq+tNYumTXV3+6A0Jc2pv1LfFWpc6ei1Q2iaLCpFjkxkqyulhduG6U+Oafgm6J",
	"bZsonsfzhQtnKtJYKUhgOY/nS4++5B7JyP1syLcyLPMXwkJy8KcZnfEqOzRzNx0f5iyOxxFufnXJX8TL",
	"PWSkfR6hdxJVBSr9tO7efjSZEXIdHsFrjVtUBd4X1MK7xrqYaOFKC7HGInAHiQMvJ37kti5L5MfDfgQ3",
	"1jHAAXXnfKKSngXnZ5IgrZlJS+AoM4LpmjzKjCUJsQu8A9cvpMY8KPeym7gl68cVngDibhrtA0ixqgqV",
	"+vTRG2uOgP2WaQ0JfBM9CW3UqWx0IGwTiLcjPI8XHy3fUNInUr7WWEtuWP1L2dF0P08BH8IaP96eMbXk",
	"HWWsFy4vWMZO8KYVthFbejO3cv7SZI8freHhh6IZKp5wTc0npNeRkk9TLIScMPNrsoNbktlluyRj+Npl",
	"CfolOiEenrfx56PNS8yCHuSvOzPemZ7kz+yNqeX04jiHqc1p7Z9ObM/H5fxugssO2A8m72VByJQF9v+R",
	"+IudZQv78TCdmz/XjqHmoru+jG8vDuru+DFW7VWmm5r7IjfhyKX2n+29j3tq7pr/AgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
