openapi: 3.0.3
info:
  title: OpenAPI
  description: OpenAPI
  termsOfService: https://localhost:8787
  contact:
    email: kotaro.otaka@example.com
  license:
    name: MIT
  version: 0.0.1
servers:
  - url: http://localhost:8787
tags:
  - name: api
    description: API
paths:
  /:
    get:
      tags:
        - api
      summary: Health
      description: Health
      operationId: health
      responses:
        "200":
          description: OK
        default:
          description: Internal Server Error
