name: CI
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
permissions: {}
env:
  GOOS: js
  GOARCH: wasm
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Restore Cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ steps.setup-go.outputs.go-version }}-
            go-
      - name: Vet (go vet)
        run: go vet ./...
      - name: Fix (go fix)
        run: go fix -diff ./...
      - name: Build (go build)
        run: go build ./...
      - name: Save Cache
        if: github.ref_name == 'main'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('go.mod') }}
